version: '3.8'

services:
  gateway:
    build:
      context: ./distribufy
      dockerfile: Dockerfile
    command: python app.py gateway
    volumes:
      - ./distribufy/services:/app/services
      - ./distribufy/logs:/app/logs
    deploy:
      replicas: ${GATEWAY_REPLICAS:-1}
    environment:
      SERVICE_NAME: gateway

  music-service:
    build:
      context: ./distribufy
      dockerfile: Dockerfile
    command: python app.py music-service
    volumes:
      - ./distribufy/services:/app/services
      - ./distribufy/logs:/app/logs
    deploy:
      replicas: ${MUSIC_SERVICE_REPLICAS:-1}
    environment:
      SERVICE_NAME: music-service

  storage-service:
    build:
      context: ./distribufy
      dockerfile: Dockerfile
    command: python app.py storage-service
    volumes:
      - ./distribufy/services:/app/services
      - ./distribufy/logs:/app/logs
    deploy:
      replicas: ${STORAGE_SERVICE_REPLICAS:-1}
    environment:
      SERVICE_NAME: storage-service

  full-dev:
    build:
      context: ./distribufy
      dockerfile: Dockerfile
    command: /bin/bash
    volumes:
      - ./distribufy:/app
    deploy:
      replicas: ${FULL_DEV_REPLICAS:-1}
    environment:
      SERVICE_NAME: full-dev